apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: mine-saker-api
  namespace: personbruker
  labels:
    team: personbruker
spec:
  envFrom:
    - secret: mine-saker-api-secrets
  image: {{version}}
  port: 8080
  liveness:
    path: /person/mine-saker-api/internal/isAlive
    initialDelay: 10
  readiness:
    path: /person/mine-saker-api/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /person/mine-saker-api/metrics
  replicas:
    min: 2
    max: 4
  webproxy: true
  idporten:
    enabled: true
  tokenx:
    enabled: true
  accessPolicy:
    outbound:
      external:
      {{#each outboundHosts}}
       - host: "{{this}}"
      {{/each}}
      rules:
        - application: safselvbetjening
          namespace: teamdokumenthandtering
          cluster: {{safselvbetjeningCluster}}
  ingresses:
    - {{ingress}}
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 580Mi
